spring.application.name=paymentsms

spring.datasource.url=jdbc:postgresql://${DB_ADDRESS}:5432/${DB_NAME}?serverTimezone=Africa/Nairobi
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.access-token.expiration-ms=${JWT_ACCESS_EXPIRATION_MS:900000}
jwt.refresh-token.expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

intasend.mpesa.checkout.url=${INTASEND_MPESA_CHECKOUT_URL}
intasend.payment.status.url=${INTASEND_PAYMENT_STATUS_URL}
intasend.sendmoney.url=${INTASEND_SENDMONEY_URL}
intasend.sendmoney.approval.url=${INTASEND_SENDMONEY_APPROVAL_URL}
intasend.sendmoney.status.url=${INTASEND_SENDMONEY_STATUS_URL}
intasend.wallet.url=${INTASEND_WALLET_URL}
intasend.secret.key=${INTASEND_SECRET_KEY}
intasend.public.key=${INTASEND_PUBLIC_KEY}

celcom.api.key=${CELCOM_API_KEY}
celcom.sms.url=${CELCOM_SMS_URL}

# Jackson Configuration - Preserve field declaration order
spring.jackson.mapper.sort-properties-alphabetically=false

#server.address=${SERVER_ADDRESS}
#server.port=${SERVER_PORT}

# test workflow
