spring.application.name=paymentsms

spring.datasource.url=jdbc:postgresql://${DB_ADDRESS:localhost}:5432/${DB_NAME:mledger}?serverTimezone=Africa/Nairobi
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:SJ8TcyS9GyK9nG2gEm7H3GVSqVTJ7jp/SD9kAGKgoB5iEMIwx26TlHgA6B2RtXe+QqwkXzagA536skCQyZ9tQQ==}
jwt.access-token.expiration-ms=${JWT_ACCESS_EXPIRATION_MS:900000}
jwt.refresh-token.expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

intasend.mpesa.checkout.url=${INTASEND_MPESA_CHECKOUT_URL:https://api.intasend.com/mpesa/checkout}
intasend.payment.status.url=${INTASEND_PAYMENT_STATUS_URL:https://api.intasend.com/payment/status}
intasend.secret.key=${INTASEND_SECRET_KEY:dummy}
intasend.public.key=${INTASEND_PUBLIC_KEY:dummy}

