-- Baseline capturing the schema as it existed before Flyway was introduced (previously managed
-- by spring.jpa.hibernate.ddl-auto=update). Existing databases are baselined at this version via
-- spring.flyway.baseline-on-migrate (this script is not re-run against them); fresh databases run
-- it like any other migration.

CREATE TABLE banks (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name           varchar(255),
    intasend_bank_code  varchar(255)
);

CREATE TABLE wallets (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(255),
    description         text,
    intasend_wallet_id  varchar(255),
    balance             numeric(38,2),
    available_balance   numeric(38,2),
    is_system_wallet    boolean,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    CONSTRAINT ukc21cmtn4jcuybk1ycmwexnuxt UNIQUE (intasend_wallet_id)
);

CREATE TABLE transactions (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_ref             varchar(255),
    invoice_id                  varchar(255),
    intasend_tracking_id        varchar(255),
    intasend_transaction_id     varchar(255),
    provider                    varchar(255),
    sender                      varchar(255),
    method                      varchar(255),
    type                        varchar(255),
    currency                    varchar(255),
    amount                      numeric(38,2),
    fee                         numeric(38,2),
    status                      varchar(255),
    narration                   text,
    notes                       text,
    failure_reason              text,
    has_batch                   boolean,
    created_at                  timestamp(6),
    updated_at                  timestamp(6),
    parent_transaction_id       bigint,
    wallet_id                   bigint,
    checkout_link               varchar(255),
    CONSTRAINT uk7ii4hpkuc8h5sccqt5wfky4na UNIQUE (transaction_ref),
    CONSTRAINT fkjabxqawmfiq6ch3b4uw6r9tp9 FOREIGN KEY (parent_transaction_id) REFERENCES transactions(id),
    CONSTRAINT fk23bop5lktue0o5q7kr19ti8h FOREIGN KEY (wallet_id) REFERENCES wallets(id)
);

CREATE TABLE transaction_callbacks (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body            text,
    created_at      timestamp(6),
    transaction_id  bigint,
    CONSTRAINT fk29p2c44f9agqsib5n1c9u2ysd FOREIGN KEY (transaction_id) REFERENCES transactions(id)
);

CREATE TABLE transaction_meta_data (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            varchar(255),
    body            text,
    created_at      timestamp(6),
    transaction_id  bigint,
    CONSTRAINT fknm95sxv76n3wbid8balpx0jv5 FOREIGN KEY (transaction_id) REFERENCES transactions(id)
);

CREATE TABLE sms_messages (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service             varchar(255),
    provider            varchar(255),
    sender              varchar(255),
    recipient           varchar(255),
    message             text,
    status              varchar(255),
    failure_reason      varchar(255),
    celcom_message_id   varchar(255),
    created_at          timestamp(6),
    updated_at          timestamp(6)
);
