CREATE TABLE api_clients (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              varchar(255) NOT NULL,
    description       text,
    api_key           varchar(255) NOT NULL,
    api_secret_hash   varchar(255) NOT NULL,
    active            boolean NOT NULL DEFAULT true,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    last_used_at      timestamp(6),
    CONSTRAINT uk_api_clients_api_key UNIQUE (api_key)
);
