CREATE TABLE celcom_senders (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shortcode         varchar(255) NOT NULL,
    partner_id        varchar(255) NOT NULL,
    api_key           varchar(255) NOT NULL,
    active            boolean NOT NULL DEFAULT true,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    CONSTRAINT uk_celcom_senders_shortcode UNIQUE (shortcode)
);
